api_platform:
    mapping:
        paths: ["%kernel.project_dir%/src/Entity"]
    patch_formats:
        json: ["application/merge-patch+json"]
    eager_loading:
        max_joins: 500
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
